repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.4.1
    hooks:
      - id: eslint
        additional_dependencies:
          - '@eslint/js'
          - 'globals'
          - 'eslint-plugin-react-hooks'
          - 'eslint-plugin-react-refresh'
          - 'typescript-eslint'
        args: ["--config", "eslint.config.js"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args: ["--skip=*.ts,*.tsx,pnpm-lock.yaml"]
